# typed: false
# frozen_string_literal: true

# This file is generated by the release workflow of
# https://github.com/jmrplens/gitlab-mcp-server — do not edit by hand.
class GitlabMcpServer < Formula
  desc "GitLab MCP server: REST v4 + GraphQL as tools for AI assistants"
  homepage "https://jmrplens.github.io/gitlab-mcp-server/"
  version "2.7.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/jmrplens/gitlab-mcp-server/releases/download/v2.7.2/gitlab-mcp-server-darwin-arm64"
      sha256 "f5a52683653469f0f1ddd4910496dc862b9d44b274efbefb6a4370fda3488b07"
    end
    on_intel do
      url "https://github.com/jmrplens/gitlab-mcp-server/releases/download/v2.7.2/gitlab-mcp-server-darwin-amd64"
      sha256 "3ed2915be0da7a0552c8f7b03bae9033ec7049a2fbbdb0dd1bc41070848c1e45"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/jmrplens/gitlab-mcp-server/releases/download/v2.7.2/gitlab-mcp-server-linux-arm64"
      sha256 "d73a905c9e3797d343aa21828596630b55b582286671273673a944fbcb366edc"
    end
    on_intel do
      url "https://github.com/jmrplens/gitlab-mcp-server/releases/download/v2.7.2/gitlab-mcp-server-linux-amd64"
      sha256 "b096a1fd74247fc619a139667cc30b99346af33653c2d861d90404d0ac1c1925"
    end
  end

  def install
    bin.install Dir["gitlab-mcp-server-*"].first => "gitlab-mcp-server"
  end

  def caveats
    <<~EOS
      Homebrew manages upgrades for this binary, so disable the built-in
      self-update in your MCP client configuration:
        AUTO_UPDATE=false

      Configure your MCP client with:
        command: #{HOMEBREW_PREFIX}/bin/gitlab-mcp-server
        env:     GITLAB_TOKEN=glpat-... (and GITLAB_URL for self-managed)

      Or run the interactive setup wizard:
        gitlab-mcp-server --setup
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gitlab-mcp-server --version")
  end
end
