# typed: false
# frozen_string_literal: true

# This file is generated by the release workflow of
# https://github.com/jmrplens/gitlab-mcp-server — do not edit by hand.
class GitlabMcpServer < Formula
  desc "GitLab MCP server: REST v4 + GraphQL as tools for AI assistants"
  homepage "https://jmrp.io/docs/gitlab-mcp-server"
  version "3.1.0"
  license "MIT"

  livecheck do
    url "https://github.com/jmrplens/gitlab-mcp-server"
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/jmrplens/gitlab-mcp-server/releases/download/v3.1.0/gitlab-mcp-server-darwin-arm64"
      sha256 "7a9f394b2bdff0d8ffae07e91a41e1e7a66aaf6be80f59da1d639f6b6327553a"
    end
    on_intel do
      url "https://github.com/jmrplens/gitlab-mcp-server/releases/download/v3.1.0/gitlab-mcp-server-darwin-amd64"
      sha256 "6f901f6b0eec7c295de7a8826b4e8ea030075ac7a05b68c03dde4f93bb297eed"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/jmrplens/gitlab-mcp-server/releases/download/v3.1.0/gitlab-mcp-server-linux-arm64"
      sha256 "bff677f20cb4afc46b1d203f2a45a752898dd3f233414ca5296ecb3521959e49"
    end
    on_intel do
      url "https://github.com/jmrplens/gitlab-mcp-server/releases/download/v3.1.0/gitlab-mcp-server-linux-amd64"
      sha256 "9bf3f52a64434f8044c02dc8dcfe674c0dc037cab21df4f1afb20e0e5722f973"
    end
  end

  def install
    bin.install Dir["gitlab-mcp-server-*"].first => "gitlab-mcp-server"
  end

  def caveats
    <<~EOS
      Homebrew manages upgrades for this binary.

      Configure your MCP client with:
        command: #{HOMEBREW_PREFIX}/bin/gitlab-mcp-server
        env:     GITLAB_TOKEN=glpat-... (and GITLAB_URL for self-managed)

      Per-client JSON:
        https://jmrp.io/docs/gitlab-mcp-server/configuration/
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gitlab-mcp-server --version")
  end
end
