# typed: false
# frozen_string_literal: true

# This file is generated by the release workflow of
# https://github.com/jmrplens/gitlab-mcp-server — do not edit by hand.
class GitlabMcpServer < Formula
  desc "GitLab MCP server: REST v4 + GraphQL as tools for AI assistants"
  homepage "https://jmrplens.github.io/gitlab-mcp-server/"
  version "2.7.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/jmrplens/gitlab-mcp-server/releases/download/v2.7.0/gitlab-mcp-server-darwin-arm64"
      sha256 "ee191f3c90c7b049cca5027a5cef39b983ea793ca56366a73fdf3fa3bce9ec5c"
    end
    on_intel do
      url "https://github.com/jmrplens/gitlab-mcp-server/releases/download/v2.7.0/gitlab-mcp-server-darwin-amd64"
      sha256 "049dcde8fd2d72311d3037fcfcbd65e4869555fc95536858c0f245193675d64c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/jmrplens/gitlab-mcp-server/releases/download/v2.7.0/gitlab-mcp-server-linux-arm64"
      sha256 "45ce39ea18a3c4923b7cd8a72efa3b59ae975e546e556a29b95636f8d760d569"
    end
    on_intel do
      url "https://github.com/jmrplens/gitlab-mcp-server/releases/download/v2.7.0/gitlab-mcp-server-linux-amd64"
      sha256 "e22d2695049faee98b246b06e56715c4935de6bdb86b5bb6b33b5e0913a77e7a"
    end
  end

  def install
    bin.install Dir["gitlab-mcp-server-*"].first => "gitlab-mcp-server"
  end

  def caveats
    <<~EOS
      Homebrew manages upgrades for this binary, so disable the built-in
      self-update in your MCP client configuration:
        AUTO_UPDATE=false

      Configure your MCP client with:
        command: #{HOMEBREW_PREFIX}/bin/gitlab-mcp-server
        env:     GITLAB_TOKEN=glpat-... (and GITLAB_URL for self-managed)

      Or run the interactive setup wizard:
        gitlab-mcp-server --setup
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gitlab-mcp-server --version")
  end
end
